### ISSUE TITLE
Fix triple variable multiplication

### ISSUE THREAD

**Issue by trk0293** [trk0293/problems#3]
armstrong fn in [https://github.com/trk0293/problems/commit/c47479fc79544bc6fa5f3e6def1c1bfd21749bbe]
`value = value + decimal*decimal*decimal;
    }
    return value+n*n*n;
`

**Comment by nanisaladi24** [comment]
Resolved in commit "fb0deb7e9b860177d584add749076c7ea0b9fafd".

**Comment by trk0293** [comment]
Thanks @nanisaladi24
